version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pruebaDB
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pruebaDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    
  db_test:
    image: postgres:16
    container_name: pruebaDB_test
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: pruebaDB_test
    ports:
        - "5433:5432"
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
      - ./init_test.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
 

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mi-servicio
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DB_HOST: postgres   
      DB_PORT: 5432          
      DB_USER: root          
      DB_PASSWORD: admin     
      DB_NAME: pruebaDB      
      PORT: 3000        
    networks:
      - app-network

volumes:
  postgres_data:
  postgres_data_test:


networks:
  app-network:
    driver: bridge